name: Software Quality Engineering CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  selenium-tests:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: selenium_automation

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Print Environment Information
        run: |
          python --version
          google-chrome --version

      - name: Run Selenium Tests
        run: |
          pytest -v -s
        continue-on-error: true

  api-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Newman
        run: |
          npm install -g newman

      - name: Run Postman Collection
        run: |
          newman run "api_testing/Software Quality Engineering API Tests.postman_collection.json"

  cypress-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cypress Run
        uses: cypress-io/github-action@v6
        with:
          working-directory: cypress_automation